# This file is part of cloudpbx-php-sdk.  The COPYRIGHT file at the top level of
# this repository contains the full copyright notices and license terms.
#
# @author (2021) Jovany Leandro G.C <jovany@picallex.com>
version: '3.4'

services:
  app:
    working_dir: /usr/src
    volumes:
      - ./:/usr/src
    environment:
      HOME: /tmp
    build:
      context: .
    network_mode:  host
